### PR TITLE
Fix --no-bail not throwing when running in default orderMode

### LINKED ISSUE #255: --no-bail flag does not exit with errors when using default order mode
The --no-bail flag does not throw when executing tasks in the default parallelGraph mode.

To reproduce: `bolt ws exec --no-bail -- false`

Whereas `bolt ws exec --no-bail --parallel -- false` works as intended

### PR DESCRIPTION
**Pull request by Blasz**
Fixes #255.

I've also improved the error message to report the number of tasks that failed and any error messages that were in the error (which is most likely going to be none for the cli version since it spawns processes).

### CODE REVIEW

File: src/Project.js [hunk 1]
```diff
@@ -197,12 +198,18 @@ export default class Project {
...
+    const taskFailures: Array<PromiseFailure> = (results.filter(
+      r => r && r.status === 'error'
+    ): any);
+    if (taskFailures.length > 0) {
+      const failuresWithMsg = taskFailures
+        .map(r => r.error && r.error.message)
+        .filter(Boolean)
+        .join('\n');
+      throw new BoltError(
+        `${taskFailures.length} tasks failed.\n${failuresWithMsg}`
```
Comment (lukebatchelor) [inline src/Project.js]: Should this live in the messages file?

**Comment by lukebatchelor** [comment]
Sweet, LGTM
