### PR TITLE
Fixes adding scoped packages with bolt add and bolt ws add

### LINKED ISSUE #40: Cannot add workspace dependency
Steps:

- Want to add latest `@atlaskit/layer-manager` dependency to the `@atlaskit/tooltip` package
- The `@atlaskit/tooltip` package.json has no `dependencies` or `devDependencies` listed, exists in `packages/elements/tooltip`
- The `@atlaskit/layer-manager` is external and is not yet use in the project
- Run `bolt w @atlaskit/tooltip add @atlaskit/layer-manager` in project root

Expected:

- `@atlaskit/layer-manager@^2.1.2` added to dependencies in the root `/package.json` 
- `@atlaskit/layer-manager@^2.1.2` added to dependencies in `/packages/elements/tooltip/package.json` 

Result:

- `@atlaskit/layer-manager@^2.1.2` added to dependencies in the root `/package.json` ✅
- `@atlaskit/layer-manager@^2.1.2` *not* added to dependencies in `/packages/elements/tooltip/package.json` ❌

Fails with output below:

```
➜  atlaskit-mk-2 git:(master) ✗ bolt w @atlaskit/tooltip add @atlaskit/layer-manager
⚡   bolt v0.14.0 (node v8.4.0)
yarn add v1.2.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "react-loadable@5.2.2" has unmet peer dependency "prop-types@*".
warning "babel-loader@7.1.2" has unmet peer dependency "babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 5 new dependencies.
├─ @atlaskit/layer-manager@2.1.2
├─ focusin@2.0.0
├─ react-gateway@2.7.0
├─ react-prop-types@0.4.0
└─ tabbable@1.1.0
✨  Done in 8.24s.
error Package "@atlaskit/tooltip" dependency "" must match version in project dependencies. "null" vs "atlaskit/layer-manager"
```

Running `bolt add @atlaskit/layer-manager` in the `/packages/elements/tooltip` directory has the same result.

### PR DESCRIPTION
**Pull request by lukebatchelor**
Resolves #40

### CODE REVIEW

File: src/commands/add.js [hunk 1]
```diff
@@ -13,17 +13,29 @@ export type AddOptions = {
...
 ): AddOptions {
   const depsArgs = [];
   let type = 'dependencies';
 
-  // args is each of our dependencies we are adding
+  // args is each of our dependencies we are adding which may have "@version" parts to them
   args.forEach(dep => {
-    const [name, version] = dep.split('@');
-    depsArgs.push(version ? { name, version } : { name });
+    depsArgs.push(options.toDependency(dep));
```
Comment (lukebatchelor) [inline src/commands/add.js]: We cooould make this a map... If you particularly care.

File: src/commands/workspace/__tests__/add.test.js [hunk 2]
```diff
@@ -14,14 +14,34 @@ jest.mock('../../../utils/logger');
...
   const depInPkgJson = pkg.getDependencyType(depName) !== null;
+  const correctVersion =
+    !version || pkg.getDependencyVersionRange(depName) === version;
 
-  return dirExists && depInPkgJson;
+  return dirExists && depInPkgJson && correctVersion;
+}
+
+// a mock yarn add function to update the pakcages's config and also node_modules dir
+async function fakeYarnAdd(pkg: Package, dependencies, type = 'dependencies') {
```
Comment (lukebatchelor) [inline src/commands/workspace/__tests__/add.test.js]: I just copied the two helped functions from the other tests as they were a bit nicer

File: src/utils/symlinkPackageDependencies.js [hunk 3]
```diff
@@ -71,10 +71,10 @@ export default async function symlinkPackageDependencies(
       valid = false;
       logger.error(
         messages.depMustMatchProject(
-          pkg.config.getName(),
-          depName,
-          versionInProject,
-          versionInPkg
+          '111',
```
Comment (lukebatchelor) [inline src/utils/symlinkPackageDependencies.js]: ...Ahhh. Yea... Let me fix this

File: src/utils/options.js [hunk 4]
```diff
@@ -33,3 +34,16 @@ export function toFilterOpts(flags: Flags) {
 
   return filterOpts;
 }
+
+/**
+ * Takes a string in one of the following forms:
+ *  "pkgName", "pkgName@version", "@scope/pkgName", "@scope/pkgName@version"
+ * and returns an object with the package name and version (if passed)
+ */
+export function toDependency(dependencyString: string): Dependency {
```
Comment (lukebatchelor) [inline src/utils/options.js]: Is this an okay place for this helper? It's used for converting a certain *kind* of flag to be typed correctly
